### ISSUE TITLE
unify.FCSheaders

### ISSUE THREAD

**Issue by Aminach1** [paiva-s-lab/FlowCT#11]
Hello,

I am encountering an issue while executing the unify.FCSheaders function. Specifically, when I set fix=F, the identification of name inconsistencies appears to be functioning correctly. In my example, three files exhibit variations in marker names.

```
library(FlowCT)
unify.FCSheaders(directory = "fresh_samples_healthy", pattern = "fcs", fix = F)
```

<img width="728" alt="unify1" src="https://github.com/paiva-s-lab/FlowCT/assets/152868589/f0b2ed04-c23a-40ae-8528-75662691ca45">
<img width="442" alt="unify2" src="https://github.com/paiva-s-lab/FlowCT/assets/152868589/0df1f32a-5cf7-4450-b702-2c247ca9241e">

However, when I set the "fix" option to TRUE, the files with inconsistencies are not replaced by the corrected versions, resulting in the following error.

```
unify.FCSheaders(directory = "fresh_samples_healthy", pattern = "fcs", fix = T)

>>> Channels:makers pattern selected for correcting:
[1] "FSC-A:NA, FSC-H:NA, SSC-A:NA, SSC-B-A:NA, SSC-B-H:NA, SSC-H:NA, FJComp-APC-A:CD127, FJComp-APC-Fire 750-A:CD11c, FJComp-APC-Fire810-A:CD38, FJComp-Alexa Fluor 647-A:CD123, FJComp-BV421-A:CCR7, FJComp-BV510-A:CD45, FJComp-BV570-A:CD3, FJComp-BV605-A:IgD, FJComp-BV650-A:CD28, FJComp-BV711-A:CD24, FJComp-BV750-A:CD56, FJComp-BV785-A:CD14, FJComp-FITC-A:CD57, FJComp-PE Fire 810-A:HLA-DR, FJComp-PE-A:TCRgd, FJComp-PE-Cy7-A:CD27, FJComp-PE-Dazzle594-A:CD34, FJComp-PE-Fire 640-A:CD19, FJComp-PE-Fire 700-A:CD25, FJComp-Pacific Blue-A:CD16, FJComp-PerCP-A:CD8, FJComp-R718-A:CD161, FJComp-Spark Blue 550-A:CD4, FJComp-Spark NIR 685-A:CD45RA, FJComp-Zombie NIR-A:viab, Time:NA"
Error in aux@exprs[, o$channels] : subscript out of bounds
```

How can I resolve this problem?
Thanks!

**Comment by jgarces02** [comment]
Hi. It's possible the error comes from the channels with "NA" instead a marker (eg, FSC-A:NA or Time:NA). Could you export the files again without including these "empty" channels that, I guess, has no marker? Thanks

**Comment by jgarces02** [comment]
I guess this is because the spaces in the channel's names. Could you please share a couple of FCS files (one for each group) and I can go into more detail? (jgarces@unav.es)
Thanks

**Comment by jgarces02** [comment]
Most probably this is because each group of files have non-overlapping channels and therefore cannnot unify names. Are these from different cytometers or with different settings?

**Comment by Aminach1** [comment]
Thank you for your prompt response.  All 11 files were measured with the same cytometer and also with the same settings (also with the same panel).

**Comment by jgarces02** [comment]
Can you send me a couple of files for each one of the groups with different headers, please? (jgarces@unav.es)

**Comment by Aminach1** [comment]
Okay, Thank you!

**Comment by jgarces02** [comment]
Hi @Aminach1, thanks for your patience. It seems that the problem with your files is the header of the second one includes additional text in front of the channels’ names and this is crashing the function.

<img width="491" alt="image" src="https://github.com/paiva-s-lab/FlowCT/assets/27858969/5784a030-d312-4b83-ad21-1f1e7de0f13b">
 
What I suggest to you is to adjust them manually through these lines:
```
file <- "flowframe2.fixed.fcs"

aux <- flowCore::read.FCS(file)
colnames(aux) <- gsub("FJComp-", "", colnames(aux))
flowCore::write.FCS(aux, filename = paste0(gsub("fcs", "", file), "fixed.fcs"))
```

**Comment by jgarces02** [comment]
I'm closing this issue. Please, feel free to re-open it again if needed. Thanks.
