### ISSUE TITLE
Installation and access issue

### ISSUE THREAD

**Issue by francescoladisa4** [paiva-s-lab/FlowCT#17]
Hello,

Thank you for your great job with FlowCT.

My Windows computer runs R 4.4.1 version. I tried to install FlowCT package by using the code you provided but R says that there is no package called "FlowCT" when it comes to access it.

Did you ever have such issue or do you know how to fix this?

Thank you

Francesco Ladisa

**Comment by jgarces02** [comment]
Hi Francesco,

Happy to hear you're using FlowCT! Could you please paste the code you used for the instalation?

**Comment by francescoladisa4** [comment]
Sure!

devtools::install_github("paiva-s-lab/FlowCT")

library(FlowCT)

**Comment by jgarces02** [comment]
Didn't you get any warning during the installation process?

**Comment by francescoladisa4** [comment]
Yes, I did:

ERROR: dependencies ‘flowCore’, ‘ncdfFlow’ are not available for package ‘FlowCT’
* removing ‘/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/FlowCT’
Warning messages:
1: packages ‘ncdfFlow’, ‘flowCore’ are not available for this version of R

Versions of these packages for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In i.p(...) :
  installation of package ‘/var/folders/2l/m7nvhbsj3k71cmgcbqyggwg40000gn/T//RtmplmeEp3/filec0512ddc47e/FlowCT_1.0.0.tar.gz’ had non-zero exit status

**Comment by jgarces02** [comment]
The problem comes from these packages, they're not installed and FlowCT's installation crashes. Try to install them before:

```
install.packages("BiocManager")
BiocManager::install(c("flowCore", "ncdfFlow"))
```

For future issues, when someone requests for the code, they're implicitly asking also for the output of it 😃

**Comment by francescoladisa4** [comment]
Thank you so much and sorry for not posting the output!

I still get warnings while installing the package

```
Downloading GitHub repo paiva-s-lab/FlowCT@HEAD
Skipping 4 packages not available: SummarizedExperiment, ncdfFlow, flowCore, SingleCellExperiment
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\franc\AppData\Local\Temp\RtmpQtqsJN\remotes5f44725867b6\paiva-s-lab-FlowCT-1ae935a/DESCRIPTION' ...
─  preparing 'FlowCT': (345ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
─  building 'FlowCT_1.0.0.tar.gz'
   
Installing package into ‘C:/Users/franc/AppData/Local/R/win-library/4.4’
(as ‘lib’ is unspecified)
ERROR: dependencies 'SingleCellExperiment', 'SummarizedExperiment' are not available for package 'FlowCT'
* removing 'C:/Users/franc/AppData/Local/R/win-library/4.4/FlowCT'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/franc/AppData/Local/Temp/RtmpQtqsJN/file5f4415e33d8c/FlowCT_1.0.0.tar.gz’ had non-zero exit status
```

**Comment by jgarces02** [comment]
All these errors are for the missing packages needed before installing _FlowCT_. Please take a look at the message error, it points out which packages are needed right now: _SingleCellExperiment_ and _SummarizedExperiment_.

The initial setting until you have _FlowCT_ running is a bit tedious; just be aware of the dependencies each error says. I'd like to do it in a more straightforward way, but I couldn't for all packages depending on Bioconductor.

**Comment by francescoladisa4** [comment]
I apologize for this, it was my fault not double checking the errors.

Thank you so much for your help!
