### ISSUE TITLE
Issues in batch removal process：object 'fcs' not found error

### ISSUE THREAD

**Issue by jfoedfjwofa** [paiva-s-lab/FlowCT#19]
Thank you very much for developing and sharing such a great module ！

I have a question about some errors encountered in the analysis of the analysis.
I want to conduct "batch removal" but the error messages appeared as following...

```
fcs_batchremoved<-batch.removal(fcs ,method = "Seurat", batch="analysis",new.matrix.name="normalized", seurat.params = list(reduction="cca",dims=1:10))
Error in FUN(X[[i]], ...) : object 'fcs' not found
```

I would appreciate it if you could provide us with as much information as possible about the cause and possible solutions.

Thank you in advance.

**Comment by jgarces02** [comment]
It seems your object has a different name than _fcs_.

**Comment by jfoedfjwofa** [comment]
> It seems your object has a different name than _fcs_.

Thank you for your prompt reply.
You mean a name of the object （SCE）for which the “batch removal” is applied to?
The name of the object is 241028_projectname_fcs, generated by fcs.sce function according to your tutrial.

Thank you so much.

**Comment by jgarces02** [comment]
```
fcs_batchremoved<-batch.removal(fcs.SCE = 241028_projectname_fcs ,method = "Seurat", batch="analysis",new.matrix.name="normalized", seurat.params = list(reduction="cca",dims=1:10))
```
