### ISSUE TITLE
Error in "colors = color_clusters"

### ISSUE THREAD

**Issue by Weide12** [paiva-s-lab/FlowCT#5]
Can not find object "colors = color_clusters"

**Comment by jgarces02** [comment]
Hi @Weide12. I guess you are following the tutorial... `color_clusters` is a variable you must create, it's not predefined within.

It's a vector with a length equal to your number of clusters:

`color_cluster <- c("red", "black", "green", ...)` (and so on until have so many as clusters you have)

**Comment by Weide12** [comment]
Thanks jgarces. This helped me. I still have some issues: 1, when run my 20 color data, "qc.and.removeDoublets" report "can not allocate 1535Gb vector"; 2, "dr.plotting" Error in melt.data.table(as.data.table(drmd), measure.vars = no.omit.markers,  : 
  'measure.vars' one or more value is invalid; 3, in heatmap plot can i order the column by condition or patient_id. Thanks.
![image](https://github.com/paiva-s-lab/FlowCT/assets/136538111/b174e795-e7b8-4d66-b9df-e1c3b5508161)

**Comment by jgarces02** [comment]
I'm glad you solved this problem.

1. That's not a new problem... it's related to RAM memory and at this time, I cannot find any solution yet. Could you use a computer with more RAM?
2. With so little information I cannot see what's happening, sorry. Please, check if you're indicating correct names in `omit.markers` options.
3. There's no implemented option in the function yet but try to order your matrix before running this function and use `clustering.method = NULL`.

**Comment by mlorenzm** [comment]
Regarding your second question, I already faced that problem, when you do not specify `color.by`on `dr.plotting.` It has to do with how your markers are named. If you have dashes (i.e. CD3-PE) on your marker names it gives that error

**Comment by jgarces02** [comment]
Indeed, @mlorenzm fixed this issue @Weide12. Maybe you can try to install the developmental version?

**Comment by Weide12** [comment]
I tried to install the developmental version using this command : devtools::install_github("jgarces02/FlowCT"), it returned an error: Error: Failed to install 'FlowCT' from GitHub:
  ! System command 'Rcmd.exe' failed

**Comment by jgarces02** [comment]
Try: `devtools::install_github("paiva-s-lab/FlowCT@develop")`

**Comment by jgarces02** [comment]
Another option is to change your marker's names to something readable by R, as @mlorenzm indicates.

> If you have dashes (i.e. CD3-PE) on your marker names it gives that error
