### ISSUE TITLE
qc.and.removeDoublet

### ISSUE THREAD

**Issue by Aminach1** [paiva-s-lab/FlowCT#9]
Hello and thanks for the algorithm.

Every time I run the function "qc.and.removeDoublet", my R session terminates abnormally.

How can I fix this problem?
Thank you very much in advance!

**Comment by jgarces02** [comment]
Hi @Aminach1, since this is the same error from this issue (#8), I gonna close this one and continue in the other one, ok?

**Comment by Aminach1** [comment]
of course, Thanks a lot
